
// This file is automatically generated. Do not edit it directly.
// Re-export the supabase client from lib/supabase.ts to maintain backward compatibility
import { supabase, isUserAdmin, formatDate } from '@/lib/supabase';

export { supabase, isUserAdmin, formatDate };
